/**
 * GENERATED by tools/generate-icons.mjs — do not edit by hand.
 * Maps vocabulary slugs to AI-generated icon paths under public/icons/ai/.
 * Regenerate by running:  node tools/generate-icons.mjs
 */

export const AI_ICONS: Record<string, string> = {
  'again': '/icons/ai/again.png',
  'all-done': '/icons/ai/all-done.png',
  'angry': '/icons/ai/angry.png',
  'apple': '/icons/ai/apple.png',
  'ball': '/icons/ai/ball.png',
  'banana': '/icons/ai/banana.png',
  'big': '/icons/ai/big.png',
  'biscuit': '/icons/ai/biscuit.png',
  'book': '/icons/ai/book.png',
  'break': '/icons/ai/break.png',
  'cold': '/icons/ai/cold.png',
  'cookie': '/icons/ai/cookie.png',
  'dad': '/icons/ai/dad.png',
  'dance': '/icons/ai/dance.png',
  'different': '/icons/ai/different.png',
  'do': '/icons/ai/do.png',
  'draw': '/icons/ai/draw.png',
  'excited': '/icons/ai/excited.png',
  'fast': '/icons/ai/fast.png',
  'finished': '/icons/ai/finished.png',
  'garden': '/icons/ai/garden.png',
  'gentle': '/icons/ai/gentle.png',
  'go': '/icons/ai/go.png',
  'good': '/icons/ai/good.png',
  'happy': '/icons/ai/happy.png',
  'helicopter': '/icons/ai/helicopter.png',
  'help': '/icons/ai/help.png',
  'here': '/icons/ai/here.png',
  'home': '/icons/ai/home.png',
  'hot': '/icons/ai/hot.png',
  'hungry': '/icons/ai/hungry.png',
  'hurt': '/icons/ai/hurt.png',
  'i': '/icons/ai/i.png',
  'juice': '/icons/ai/juice.png',
  'like': '/icons/ai/like.png',
  'listen': '/icons/ai/listen.png',
  'little': '/icons/ai/little.png',
  'look': '/icons/ai/look.png',
  'milkshake': '/icons/ai/milkshake.png',
  'more': '/icons/ai/more.png',
  'mum': '/icons/ai/mum.png',
  'music': '/icons/ai/music.png',
  'my-turn': '/icons/ai/my-turn.png',
  'my': '/icons/ai/my.png',
  'no': '/icons/ai/no.png',
  'not': '/icons/ai/not.png',
  'outside': '/icons/ai/outside.png',
  'play': '/icons/ai/play.png',
  'please': '/icons/ai/please.png',
  'sad': '/icons/ai/sad.png',
  'sandwich': '/icons/ai/sandwich.png',
  'scared': '/icons/ai/scared.png',
  'share': '/icons/ai/share.png',
  'sing': '/icons/ai/sing.png',
  'slow': '/icons/ai/slow.png',
  'snack': '/icons/ai/snack.png',
  'sorry': '/icons/ai/sorry.png',
  'stop': '/icons/ai/stop.png',
  'swimming': '/icons/ai/swimming.png',
  'teacher': '/icons/ai/teacher.png',
  'thank-you': '/icons/ai/thank-you.png',
  'thirsty': '/icons/ai/thirsty.png',
  'this': '/icons/ai/this.png',
  'tired': '/icons/ai/tired.png',
  'toilet': '/icons/ai/toilet.png',
  'tooth': '/icons/ai/tooth.png',
  'turn': '/icons/ai/turn.png',
  'wait': '/icons/ai/wait.png',
  'walk': '/icons/ai/walk.png',
  'want': '/icons/ai/want.png',
  'water': '/icons/ai/water.png',
  'what': '/icons/ai/what.png',
  'where': '/icons/ai/where.png',
  'yes': '/icons/ai/yes.png',
  'you': '/icons/ai/you.png',
  'your-turn': '/icons/ai/your-turn.png',
}

function slugify(label: string): string {
  return label
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

/** Case-insensitive lookup: the icon path for a label, or null if none exists. */
export function aiIconFor(label: string): string | null {
  return AI_ICONS[slugify(label)] ?? null
}
