/**
 * GENERATED by tools/generate-icons.mjs — do not edit by hand.
 * Maps vocabulary slugs to AI-generated icon paths under public/icons/ai/.
 * Regenerate by running:  node tools/generate-icons.mjs
 */

export const AI_ICONS: Record<string, string> = {
}

function slugify(label: string): string {
  return label
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

/** Case-insensitive lookup: the icon path for a label, or null if none exists. */
export function aiIconFor(label: string): string | null {
  return AI_ICONS[slugify(label)] ?? null
}
